[template]
src = "es.conf.tmpl"
dest = "/etc/apache2/conf.d/elasticsearch.conf"
prefix = "/voice-stage/stage"

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/*",
    "/config"
]

reload_cmd = "/bin/systemctl stop apache2; /bin/systemctl start apache2"
