[template]
src = "river.toml.tmpl"
dest = "/etc/river.toml"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/*",
    "/config"
]

# For now, enable in stage only
reload_cmd = "if nubis-purpose sync && [ $(nubis-metadata NUBIS_ENVIRONMENT) == stage ] ; then systemctl restart go-mysql-elasticsearch; else true; fi"
