[template]
src = "voice.json.tmpl"
dest = "/var/www/voice/server/config.json"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/*",
    "/config"
]

reload_cmd = "/sbin/reload voice || /sbin/restart voice || /sbin/start voice"
