[template]
src = "voice.json.tmpl"
dest = "/var/www/voice/config.json"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/*",
    "/config"
]

reload_cmd = "/bin/systemctl restart voice || /bin/systemctl start voice"
